apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.1.0
          env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          ports:
            - containerPort: 9092
          resources:
            limits:
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
  selector:
    name: kafka
